services:
  - type: web
    name: vcure-backend
    env: node
    region: singapore
    plan: free
    rootDir: vcure-backend-complete/acc3
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SUPABASE_URL
        value: https://mlmlhnealtveagtvbhqw.supabase.co
      - key: SUPABASE_STORAGE_BUCKET
        value: medical-reports
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
